### ISSUE TITLE
Add ~~ to all non-translated items

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-android#2]
Everything in Crisis Cleanup should be localized. When creating new text, please add a double-tilde inside a translate declaration, so that I can easily search for the ~~ and replace the string with the translation tag.
Example: `translate("~~You are not connected to the internet")`
I would later come back and change this to something like `translate("info.not_connected_internet")`

Please note, this includes strings like found in https://github.com/CrisisCleanup/crisiscleanup-android/blob/main/app/src/main/res/values/strings.xml. So you'll probably need to find some other way to store the information than xml.

**Comment by aarontitus** [comment]
No, don't worry about that. You can use any text off the top of your head. Just prefix it with ~~, and that will allow me to find it and make any changes I'd like.
But if you would please include the correct syntax for translating, that would be very helpful.

**Comment by hueachilles** [comment]
I've updated most texts to using translations. Text without translations will have the `~~` except for RRule related texts. We can go over this set of translations during mobile standup.
These files have text where translations are needed. Some translations are not necessary because the user should never see these (error) messages if the app is functioning properly. I have these messages more for context clues if they're ever reported I'll know where the issue stems from.
* [App](https://github.com/CrisisCleanup/crisiscleanup-android/blob/main/app/src/main/res/values/strings.xml)
* [Menu](https://github.com/CrisisCleanup/crisiscleanup-android/blob/main/feature/menu/src/main/res/values/strings.xml)
* [Auth](https://github.com/CrisisCleanup/crisiscleanup-android/blob/main/feature/authentication/src/main/res/values/strings.xml)
* [Case](https://github.com/CrisisCleanup/crisiscleanup-android/blob/main/feature/cases/src/main/res/values/strings.xml)
* [Edit case](https://github.com/CrisisCleanup/crisiscleanup-android/blob/main/feature/caseeditor/src/main/res/values/strings.xml). This has the RRule texts that need translation but are not annotated with `~~`.
* [Sync](https://github.com/CrisisCleanup/crisiscleanup-android/blob/main/sync/work/src/main/res/values/strings.xml). These are not annotated with `~~` but all need translations. These texts show up in notifications.

**Comment by arroyoDev** [comment]
looks good.   approving until further notice.
